import numpy as np

color_categories = {
    '화이트': np.array(255,255,255),
    '블랙': np.array(0,0,0),
    '그레이': np.array(178,178,178),
    '네이비': np.array(0,32,102),
    '블루': np.array(39,47,255),
    '아이보리': np.array(254,254,237),
    '라이트그레이': np.array(217,217,215),
    '베이지':np.array(241,194,118),
    '그린':np.array(),
    '다크그레이':np.array(),
    '스카이블루':np.array(),
    '브라운':np.array(),
    '옐로우':np.array(),
    '카키':np.array(),
    '민트':np.array(),
    '레드':np.array(),
    '오렌지':np.array(),
    '핑크':np.array(),
    '퍼플':np.array(),
    '다크그린':np.array(),
    '라벤더':np.array(),
    '올리브그린':np.array(),
    '라이트핑크':np.array(),
    '라이트그린':np.array(),
    '라이트옐로우':np.array(),
    '페일핑크':np.array(),
    '버건디':np.array(),
    '데님':np.array(),
    '카멜':np.array(),
    '딥레드':np.array(),
    '카키베이지':np.array(),
    '연청':np.array(),
    '중청':np.array(),
    '진청':np.array(),
    '흑청':np.array()   
}